CREATE TABLE IF NOT EXISTS payments (
    id UUID PRIMARY KEY,
    order_id UUID UNIQUE NOT NULL,
    amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    method VARCHAR(50) NOT NULL DEFAULT 'card',
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
